### PR TITLE
Ensure the consent overlay is clickable.

### PR DESCRIPTION
**Pull request by robindevitt**
#### Issue
The clickable areas for the cookie category overlay does not align with the displayed checkboxes and labels.
Original Issue [#991](https://github.com/humanmade/product-dev/issues/991)

#### Solution
This PR ensure the consent overlay is clickable by setting the conflicting div to position relative.

#### Steps to confirm
1. Go to Any page on the site with out cookies set up so the Consent popup appears
2. Click on Cookie Preferences
3. You should now be able to click any of the check boxes & the labels

#### Screenshare

https://user-images.githubusercontent.com/16571365/161746867-bfe9cc7c-6202-4560-81f0-de414f0e7b4e.mov

### CODE REVIEW

**Comment by robindevitt** [comment]
Shall I clean up the HM Linter changes too despite not being related to this issue? Most of them look pretty straight forward except for the one where the "Expected nesting depth to be no more than 2 (max-nesting-depth)", that change may be a bit more indepth.

**Comment by roborourke** [comment]
I'd make a separate PR to clean up the linter errors I think, they're all on the minified CSS file and HM Linter seems to not work with `.stylelintignore` files so we'd need to see if the build tools can add a line like `/* stylelint-disable */` to the start of the built CSS file.

**Comment by roborourke** [comment]
Were you able to replicate the issue on the theme in your video? Also did you test this fix with the twenty twenty two theme used in @mikelittle's video?

**Comment by robindevitt** [comment]
> Were you able to replicate the issue on the theme in your video? Also did you test this fix with the twenty twenty two theme used in @mikelittle's video?

I was able to replicate it with Twenty Nineteen. I tried now and replicated and confirmed the fix with Twenty Twenty Two ( video added below ).

https://user-images.githubusercontent.com/16571365/161752828-117bd2c2-849b-4e51-8950-44b341af457b.mov

**Review by mikelittle — APPROVED** [review]
Looks good to me

**Comment by robindevitt** [comment]
HM Linter bot changes have been implemented 👍🏼

**Review by roborourke — APPROVED** [review]

**Comment by roborourke** [comment]
@robindevitt don't forget to make a new patch release if you haven't done it already!

**Comment by robindevitt** [comment]
Thanks @roborourke Got it now 👍🏼

**Comment by robindevitt** [comment]
@roborourke I may have done this incorrectly ... is a patch release the same as a tag release?

**Comment by roborourke** [comment]
No you did it right, I'll do an internal write up on semver versioning to help.

**Pull request merged**
