### PR TITLE
remove docs

### PR DESCRIPTION
**Pull request by jazzsequence**
moved to privacy module

### CODE REVIEW

**Comment by roborourke** [comment]
Is this to avoid duplication. To be fair we do have some cases like the `aws-analytics` plugin where it's a plugin in its own right and can work without Altis so there may still be value in having docs on this repo. Unless you feel that the main `README.md` is enough.

**Comment by jazzsequence** [comment]
We have the wiki, which already duplicates these docs in this repo, if people come here to look for stuff. Otherwise, I'm thinking when this gets merged that consent would/should be under the main Privacy header. Would that get pulled in automatically for dependencies?

**Comment by roborourke** [comment]
Ah alright then, if it's all in the wiki and the readme for this plugin points to that then there's no need to keep them around.

Dependency docs are not pulled in, only module docs are shown automatically. I was just questioning removing the docs from here if it would make the repo less useful on its own.

**Review by roborourke — APPROVED** [review]

**Comment by jazzsequence** [comment]
I'll make sure the readme in the repo points to the wiki docs 👍

**Pull request merged**
